### ISSUE TITLE
 New component: Input

### ISSUE THREAD

**Issue by lucasaugustsof** [guhrodriguess/luxe#10]
I prototyped a new component and wanted your approval @guhrodriguess regarding the quality standards of Luxe components.

![Screenshot 2024-02-21 at 21 05 36](https://github.com/guhrodriguess/luxe/assets/71651661/7694a93a-994b-4eea-9b09-219ae5166757)

https://github.com/guhrodriguess/luxe/assets/71651661/8d692763-60d7-4f3e-97ac-0111f24da7f4

**Comment by guhrodriguess** [comment]
That's incredible, @lucasaugustsof!
