### ISSUE TITLE
feat: allow you to edit and test the code

### ISSUE THREAD

**Issue by euotiniel** [guhrodriguess/luxe#12]
It would be interesting to be able to have a kind of editor to be able to style and modify the code before copying.

Look at an example here:

```before:```

![Captura de Ecrã (653)](https://github.com/guhrodriguess/luxe/assets/93485038/40559c7f-eca4-4f25-a36e-3e82f83111f1)

```after:```

![Captura de Ecrã (654)](https://github.com/guhrodriguess/luxe/assets/93485038/f41a58eb-ffe0-4e5b-8329-0076953ff20f)

> And no, I didn't inspect and change it. 😂

```errors:```

![Captura de Ecrã (655)](https://github.com/guhrodriguess/luxe/assets/93485038/32db695d-5e40-4eb7-a6b6-b49523147cba)

---

Visit here: [link](https://vercel.com/design/button)

**Comment by lucasaugustsof** [comment]
I found the idea cool... Do you know where to start?

**Comment by euotiniel** [comment]
There must be some lib for this, we found out what it is and that's it. I'll search npm.

**Comment by guhrodriguess** [comment]
Good idea, @euotiniel! I'll arrange it.

**Comment by euotiniel** [comment]
@guhrodriguess and @lucasaugustsof , Have you been working on this feat?

**Comment by lucasaugustsof** [comment]
Not yet... I believe @guhrodriguess is fixing some bugs :/
