### ISSUE TITLE
Button Animated Border

### ISSUE THREAD

**Issue by SikandarJODD** [guhrodriguess/luxe#17]
Link : https://luxe.guhrodrigues.com/ui/button-animated-border

This component doesn't work like the border thing...
I copied the code mentioned ...but it didn't work

**Comment by guhrodriguess** [comment]
Have you put the keyframe settings in tailwind.config?

**Comment by SikandarJODD** [comment]
i found it..it was due to naming convention `rotate` ...i changed to : kitrotate ...own naming convention..and it work

**Comment by SikandarJODD** [comment]
Thanks @guhrodriguess, Thanks a lottttttt..luxe components really helped me a lot..i was actually in search for this components

**Comment by SikandarJODD** [comment]
I find interesting thing : https://github.com/tailwindlabs/tailwindcss-aspect-ratio
if u implement this, `button animated border` component doesn't work and if we remove it, it' works well
