### ISSUE TITLE
Responsive Card Comment 

### ISSUE THREAD

**Issue by SikandarJODD** [guhrodriguess/luxe#18]
## Issue Link 
https://luxe.guhrodrigues.com/ui/card-comment

when users view this component on mobile devices the gradient line overflows the `CardComment` 

## Solution :
 - Add `overlfow-hidden`  in `CardComment.tsx` : line-no : 5
 - Component : https://github.com/guhrodriguess/luxe/blob/main/src/app/_components/ui/cards/CardComment.tsx
### Image 
![image](https://github.com/guhrodriguess/luxe/assets/93428946/a0fa8910-5b33-4b04-97e7-31fe123b7361)

**Comment by guhrodriguess** [comment]
Thanks, man!
